### PR TITLE
Misc: add component structure

### PR DESCRIPTION
**Pull request by daoneandonly**
## Issue
Add Component Structure

Closes: #20 

### Changes 🛠
* Add folders for `atoms`, `molecules`, `organisms`
* Add `.md` files to explain what these groups mean.
* Move all files to `src` directory
* Add `atoms/Test` component to check functionality of Components and file structure. This can be removed once we start working on components.

### Notes ⚠
* SCSS is not yet implemented, and we should do this asap.
* Only relative paths currently work for importing components. We should have root declared as root of the project so we can import as `src/components/atoms/Test`

### CODE REVIEW

**Comment by aaraar** [comment]
https://turn-order-tracker-d8xwf02pm.vercel.app/

**Review by aaraar — APPROVED** [review]
Nice

**Comment by aaraar** [comment]
Oh damn die preview link wordt gecomment, wat nice

**Comment by daoneandonly** [comment]
> Oh damn die preview link wordt gecomment, wat nice

Yes heel nice idd!

**Pull request merged**
